INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('CR90 corvette',950,150);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Star Destroyer',975,1600);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Sentinel-class landing craft',1000,38);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Death Star',0,120000);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Millennium Falcon',1050,34.37);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Y-wing',0,14);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('X-wing',1050,12.5);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Imperial shuttle',850,20);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Republic Cruiser',900,115);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Droid control ship',0,3170);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Naboo fighter',1100,11);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Naboo Royal Starship',920,76);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Scimitar',1180,26.5);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Slave 1',1000,21.5);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('J-type diplomatic barge',2000,39);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('AA-9 Coruscant freighter',0,390);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Jedi starfighter',1150,8);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Trade Federation cruiser',1050,1088);
INSERT INTO STARSHIP (NAME,MAX_SPEED,LENGTH) VALUES ('Theta-class T-2c shuttle',2000,18.5);

INSERT INTO FILMS(TITLE) VALUES ('A New Hope');
INSERT INTO FILMS(TITLE) VALUES ('The Empire Strikes Back');
INSERT INTO FILMS(TITLE) VALUES ('Return of the Jedi');
INSERT INTO FILMS(TITLE) VALUES ('The Phantom Menace');
INSERT INTO FILMS(TITLE) VALUES ('Attack of the Clones');
INSERT INTO FILMS(TITLE) VALUES ('Revenge of the Sith');

INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(1,1);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(2,1);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(3,1);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(4,1);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(5,1);

INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(2,2);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(5,2);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(6,2);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(7,2);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(8,2);

INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(1,3);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(2,3);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(5,3);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(6,3);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(7,3);

INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(9,4);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(10,4);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(11,4);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(12,4);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(13,4);

INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(14,5);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(10,5);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(11,5);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(15,5);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(16,5);

INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(1,6);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(10,6);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(17,6);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(18,6);
INSERT INTO STARSHIP_FILMS(STARSHIP_ID,FILM_ID) VALUES(19,6);

INSERT INTO PRODUCERS (NAME) VALUES ('Gary Kurtz');
INSERT INTO PRODUCERS (NAME) VALUES ('Rick McCallum');
INSERT INTO PRODUCERS (NAME) VALUES ('Howard G. Kazanjian');
INSERT INTO PRODUCERS (NAME) VALUES ('George Lucas');

INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (1,1);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (1,2);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (2,1);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (2,2);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (3,1);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (3,1);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (3,2);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (4,2);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (5,2);
INSERT INTO FILMS_PRODUCERS (FILM_ID, PRODUCER_ID) VALUES (6,2);