CREATE table STARSHIP
(
    ID        IDENTITY PRIMARY KEY NOT NULL,
    NAME      VARCHAR(255)    NOT NULL,
    MAX_SPEED INT             NOT NULL,
    LENGTH    FLOAT           NOT NULL
);

CREATE table FILMS
(
    ID    IDENTITY PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255)    NOT NULL
);

CREATE TABLE STARSHIP_FILMS
(
    FILM_ID     INT NOT NULL,
    STARSHIP_ID INT NOT NULL,
    FOREIGN KEY (FILM_ID) REFERENCES FILMS (ID),
    FOREIGN KEY (STARSHIP_ID) REFERENCES STARSHIP (ID)
);

CREATE TABLE PRODUCERS
(
    ID   IDENTITY PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)    NOT NULL
);

CREATE TABLE FILMS_PRODUCERS
(
    FILM_ID     INT NOT NULL,
    PRODUCER_ID INT NOT NULL,
    FOREIGN KEY (FILM_ID) REFERENCES FILMS (ID),
    FOREIGN KEY (PRODUCER_ID) REFERENCES PRODUCERS (ID)
);